language: php
dist: xenial

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly

matrix:
  include:
    - php: '5.5'
      dist: trusty
  allow_failures:
    - php: nightly

install: composer install
script: composer test
